### PR TITLE
Fix/exception on reading folder

### PR DESCRIPTION
**Pull request by philipjmurphy**
I noticed that when a new folder is created that an exception is thrown in the console.

```
e.g.  (node:41829) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:568:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at FSWatcher.<anonymous> (/Users/<username>/.nvm/versions/node/v12.20.1/lib/node_modules/blazepack/src/commands/start-dev-server/index.js:204:28)
```

This addition fixes the issue.

PS My VS Code 'Code Spell Checker' extension noticed a few typos which I've corrected :)

### CODE REVIEW

**Comment by ameerthehacker** [comment]
awesome thanks for the contribution @philipjmurphy

**Comment by ameerthehacker** [comment]
@philipjmurphy your fix has been released in v0.0.18 please check and let me know

**Comment by philipjmurphy** [comment]
Looks good - nice one.

**Comment by ameerthehacker** [comment]
@all-contributors please add @philipjmurphy for bug

**Pull request merged**
